adding ibmcloud postsubmit job
ppc64le-cloud/test-infra pull request #125
Opened 2021-02-02 12:59 UTC by RagniGarg97

2021-02-02 12:59 UTC, ltccci commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/ppc64le-cloud/test-infra/pull/125#" title="Author self-approved">RagniGarg97</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **mkumatag** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @mkumatag` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=ppc64le-cloud%2Ftest-infra).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/ppc64le-cloud/test-infra/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["mkumatag"]} -->

2021-02-02 13:00 UTC, RagniGarg97 commented
/cc @mkumatag

2021-02-02 13:28 UTC, mkumatag requested changes

2021-02-02 13:28 UTC, mkumatag commented on config/jobs/ppc64le-cloud/ibmcloud-postsubmit.yaml
> +                kubectl build --push --registry-secret quay-powercloud-regcred --namespace image-builder --build-arg ARCH=amd64 -t quay.io/powercloud/ibm-cloud:amd64-latest -f Dockerfile ./
- why do we need `--build-arg ARCH=amd64`?
- we don't need `amd64` in the image tag

2021-02-03 10:56 UTC, mkumatag commented
/lgtm
/approve

2021-02-03 10:56 UTC, ltccci commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/ppc64le-cloud/test-infra/pull/125#issuecomment-772420102" title="Approved">mkumatag</a>*, *<a href="https://github.com/ppc64le-cloud/test-infra/pull/125#" title="Author self-approved">RagniGarg97</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=ppc64le-cloud%2Ftest-infra).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/ppc64le-cloud/test-infra/blob/master/OWNERS)~~ [mkumatag]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2021-02-03 10:57 UTC, merged

2021-02-03 10:57 UTC, ltccci commented
@RagniGarg97: Updated the `job-config` configmap in namespace `prow` at cluster `default` using the following files:
 - key `ibmcloud-postsubmit.yaml` using file `config/jobs/ppc64le-cloud/ibm-cloud/ibmcloud-postsubmit.yaml`

<details>

In response to [this](https://github.com/ppc64le-cloud/test-infra/pull/125):

>post-submit job to build ibm-cloud image.
>https://github.com/ppc64le-cloud/test-infra/blob/master/images/ibm-cloud/Dockerfile
>
>Fixes: #118 


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>