bump the terraform version
ppc64le-cloud/test-infra pull request #172
Opened 2021-04-12 11:58 UTC by RagniGarg97

2021-04-12 11:58 UTC, ltccci commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/ppc64le-cloud/test-infra/pull/172#" title="Author self-approved">RagniGarg97</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **mkumatag** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @mkumatag` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=ppc64le-cloud%2Ftest-infra).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/ppc64le-cloud/test-infra/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["mkumatag"]} -->

2021-04-13 02:04 UTC, mkumatag requested changes

2021-04-13 02:04 UTC, mkumatag commented on images/all-in-one/Dockerfile
> +ENV TF_VERSION ${TF_VERSION:-v0.13.0}
Better update with the latest 0.13.x version available

2021-04-14 05:30 UTC, mkumatag commented
remove draft when it is ready for review

/cc @Rajalakshmi-Girish

2021-04-15 07:07 UTC, RagniGarg97 commented
/remove do-not-merge

2021-04-15 12:38 UTC, Rajalakshmi-Girish commented
> 
> 
> _No description provided._

@mkumatag we plan to have Terraform plugins installation as part of the `all-in-one` image as this is repeatedly needed by all the conformance jobs that use Terraform. Hope it is fine.
I am verifying the changes made by Ragni. Will remove draft once done.

2021-04-15 12:42 UTC, mkumatag commented
> > 
> > 
> > _No description provided._
> 
> @mkumatag we plan to have Terraform plugins installation as part of the `all-in-one` image as this is repeatedly needed by all the conformance jobs that use Terraform. Hope it is fine.
> I am verifying the changes made by Ragni. Will remove draft once done.

Okay

2021-04-15 14:16 UTC, closed without merging