Adding containerd-node-throughput job config
ppc64le-cloud/test-infra pull request #196
Opened 2021-06-09 11:04 UTC by piyushgupta1551

Adding node-throughput prow job config

2021-06-09 16:02 UTC, piyushgupta1551 commented
/cc @mkumatag 
/assign @piyushgupta1551

2021-06-10 13:05 UTC, mkumatag requested changes

2021-06-10 13:05 UTC, mkumatag commented on config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
> +              pushd /tmp;git clone https://github.com/kubernetes/perf-tests.git
can you put these changes into `extra_refs` section which take care of git cloning

2021-06-10 13:05 UTC, mkumatag commented on config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
> +                --powervs-image-name centos-83-12142020 \
we already have an image in the tier1 with name `centos-83-03222021-tier1`, you can mentioned that here

2021-06-10 13:05 UTC, mkumatag commented on config/prow/perfdash/perfdash-deployment.yaml
> +  namespace: perfdash
It will be good if you can submit this change in a different PR

2021-06-10 13:06 UTC, mkumatag commented
/cc @Rajalakshmi-Girish

2021-06-11 06:10 UTC, piyushgupta1551 commented
Closing this PR. Will raise 2 new ones with review comments as I need to delete my fork and redo the changes due to branch conflicts at my end.

2021-06-11 06:10 UTC, closed without merging