Adding Storage Job
ppc64le-cloud/test-infra pull request #235
Opened 2021-09-28 10:35 UTC by piyushgupta1551

- Adds Storage Job with 3h interval
- Changes interval of containderd-node-throughput from 3h to 12h

Test Run logs - https://storage.googleapis.com/ppc64le-kubernetes/logs/periodic-kubernetes-storage-perf-test-ppc64le/1442719842799980544/build-log.txt

2021-09-28 11:14 UTC, mkumatag requested changes
Tests are failing with errors likes:

```
action gather failed for MetricsForE2E measurement: errors while grabbing metrics: [the server is currently unable to handle the request (get pods https:kube-scheduler-perf-test-1632806312-master:10259) error waiting for controller manager pod to expose metrics: timed out waiting for the condition; the server is currently unable to handle the request (get pods https:kube-controller-manager-perf-test-1632806312-master:10257)]]
```

```
E0928 06:18:03.260137    9526 clusterloader.go:227] --------------------------------------------------------------------------------
E0928 06:18:03.260143    9526 clusterloader.go:228] Test Finished
E0928 06:18:03.260150    9526 clusterloader.go:229]   Test: secret-vol-per-node(testing/experimental/storage/pod-startup/config.yaml)
E0928 06:18:03.260156    9526 clusterloader.go:230]   Status: Fail
E0928 06:18:03.260162    9526 clusterloader.go:232]   Errors: [measurement call TestMetrics - TestMetrics error: [action start failed for SchedulingMetrics measurement: the server is currently unable to handle the request (get pods https:kube-scheduler-perf-test-1632806312-master:10259)]
measurement call TestMetrics - TestMetrics error: [action gather failed for SchedulingMetrics measurement: the server is currently unable to handle the request (get pods https:kube-scheduler-perf-test-1632806312-master:10259)
action gather failed for MetricsForE2E measurement: errors while grabbing metrics: [the server is currently unable to handle the request (get pods https:kube-scheduler-perf-test-1632806312-master:10259) error waiting for controller manager pod to expose metrics: timed out waiting for the condition; the server is currently unable to handle the request (get pods https:kube-controller-manager-perf-test-1632806312-master:10257)]]]
```

With these errors, I'm not really sure will get any numbers?!

2021-09-29 05:38 UTC, piyushgupta1551 commented
Hi @mkumatag , The failure is not impacting the overall results in a major way. We still get the required results. Ref - https://console.cloud.google.com/storage/browser/ppc64le-kubernetes/logs/periodic-kubernetes-storage-perf-test-ppc64le/1442719842799980544/artifacts;tab=objects?prefix=&forceOnObjectsSortingFiltering=false

The same module step fails in upstream as well in each run but it is not breaking the test or result collection in any major way. Ref - https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-storage-scalability/1433969021937520640/build-log.txt

2021-09-29 05:47 UTC, mkumatag commented
> Hi @mkumatag , The failure is not impacting the overall results in a major way. We still get the required results. Ref - https://console.cloud.google.com/storage/browser/ppc64le-kubernetes/logs/periodic-kubernetes-storage-perf-test-ppc64le/1442719842799980544/artifacts;tab=objects?prefix=&forceOnObjectsSortingFiltering=false
> 
> The same module step fails in upstream as well in each run but it is not breaking the test or result collection in any major way. Ref - https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-storage-scalability/1433969021937520640/build-log.txt

cool. 👍🏽

2021-09-29 05:47 UTC, mkumatag approved these changes
/lgtm
/approve

2021-09-29 05:48 UTC, merged