[WIP]Clean up stale Hypershift VMs
ppc64le-cloud/test-infra pull request #442
Opened 2024-02-02 14:34 UTC by Neha-dot-Yadav

This PR has a periodic job which cleans up all stale VMs present in Hypershift `rh-upstream-hypershift-agent-ci` , `rh-upstream-hypershift-cluster-bot-pvs` , `rh-upstream-hypershift-powervs-ci-e2e-pvs` service instances which are older than 24h(1 day).

2024-02-02 15:15 UTC, mkumatag requested changes
please remove all these .DS_Store files

2024-02-02 15:16 UTC, mkumatag commented
/cc @Rajalakshmi-Girish

please review this PR when its ready

2024-02-05 09:05 UTC, Rajalakshmi-Girish requested changes
@Neha-dot-Yadav I see the last line [#28](https://github.com/ppc64le-cloud/test-infra/pull/442/files#diff-e1e060021fdbbb1dd86dbb4a11540c2248afc0c90cfe33bc1da04850fc6dbed3R28 ) commented out.
But, you have mentioned the ID's related service instance name `rh-upstream-hypershift-agent-ci` in the description of this change.
Would like like to uncomment last line?

2024-02-05 09:08 UTC, Rajalakshmi-Girish commented
Also, have you tried testing this job by running `test-pj` liken mentioned [here](https://github.com/ppc64le-cloud/test-infra#method-2-test-on-the-already-deployed-kubernetes-cluster)? Let me know if you want me to run it before merging

2024-02-05 09:09 UTC, Neha-dot-Yadav commented
> @Neha-dot-Yadav I see the last line [#28](https://github.com/ppc64le-cloud/test-infra/pull/442/files#diff-e1e060021fdbbb1dd86dbb4a11540c2248afc0c90cfe33bc1da04850fc6dbed3R28) commented out. But, you have mentioned the ID's related service instance name `rh-upstream-hypershift-agent-ci` in the description of this change. Would like like to uncomment last line?

Have commented it just for testing, as with the current purge condition, the bastian VM is also getting deleted(as it was created before 24h). So, looking at, how we can make it conditional to exclude that VM.

2024-02-05 09:12 UTC, Neha-dot-Yadav commented
> Also, have you tried testing this job by running `test-pj` like it is mentioned [here](https://github.com/ppc64le-cloud/test-infra#method-2-test-on-the-already-deployed-kubernetes-cluster)? Let me know if you want me to run it before merging

@Rajalakshmi-Girish have not tested it yet, as still working adding that condition.
Let's hold the merge till then.

2024-02-05 09:37 UTC, Rajalakshmi-Girish commented
> Have commented it just for testing, as with the current purge condition, the bastian VM is also getting deleted(as it was created before 24h). So, looking at, how we can make it conditional to exclude that VM.

I see pvsadm having a flag `--regexp` string                    `Regular Expressions for filtering the selection`
If your VMs from CI have a common name to filter out, you many use this regexp flag and delete only those. (I haven't tried using this flag earlier :| )

2024-02-05 09:38 UTC, Neha-dot-Yadav commented
> > Have commented it just for testing, as with the current purge condition, the bastian VM is also getting deleted(as it was created before 24h). So, looking at, how we can make it conditional to exclude that VM.
> 
> I see pvsadm having a flag `--regexp` string `Regular Expressions for filtering the selection` If your VMs from CI have a common name to filter out, you many use this regexp flag and delete only those. (I haven't tried using this flag earlier :| )

Thanks, using that approach, and testing it.
Let's see!

2024-02-16 08:47 UTC, Rajalakshmi-Girish approved these changes
/lgtm

2024-02-16 08:48 UTC, Rajalakshmi-Girish commented
Was tested by running `test-pj`
https://prow.ppc64le-cloud.cis.ibm.net/job-history/s3/ppc64le-prow-logs/logs/test-periodic-hypershift-powervs-cleanup

2024-02-16 08:56 UTC, Rajalakshmi-Girish commented
/approve

2024-02-16 09:34 UTC, merged