Update hypershift-powervs-cleanup job to clean new infra
ppc64le-cloud/test-infra pull request #492
Opened 2024-10-21 16:08 UTC by Neha-dot-Yadav

The PowerVS Workspace for `Clusterbot` and `Powervs-e2e-ci` are updated to accommodate transit-gateway related changes.
So, this PR updates `hypershift-powervs-cleanup` job's purge command with new instance-ids.

Testing:
The purge command was tested manually with both new service-ids.

2024-10-21 16:26 UTC, mkumatag requested changes
can you please add the workspace names in the comment so that it becomes little easier later when recreate these in future.

@Rajalakshmi-Girish can you please ensure that the API Key used for cleaning these workspaces got a right authz.

2024-10-21 16:35 UTC, Neha-dot-Yadav commented
@mkumatag updated the names.

2024-10-21 17:10 UTC, mkumatag commented
> @mkumatag updated the names.

I mean in the code itself with the comment(`#`)

2024-10-21 17:12 UTC, Rajalakshmi-Girish approved these changes
/lgtm

2024-10-21 17:13 UTC, Rajalakshmi-Girish commented
/hold

2024-10-21 17:21 UTC, Rajalakshmi-Girish commented
> @Rajalakshmi-Girish can you please ensure that the API Key used for cleaning these workspaces got a right authz.

@mkumatag I am not authorized to view the service ID related to APIKey.

But, based on my previous discussion with her, @Neha-dot-Yadav  must have created service id by name `cleanup-hypershift` with ACL as below:

Manager, Viewer Role for Workspace for Power Virtual Server service in `ibm-hypershift-dev` resource group

2024-10-22 03:11 UTC, mkumatag approved these changes
/lgtm

2024-10-22 03:11 UTC, mkumatag commented
/unhold

2024-10-22 03:13 UTC, merged